require('mirgee.plugins')
require('mirgee.opts')
require('mirgee.keymaps')
require('mirgee.autocmds')

require('mirgee.configs.lspconfig')
require('mirgee.configs.copilot')
require('mirgee.configs.fzf')
require('mirgee.configs.rust')
require('mirgee.configs.nvim-tree')
require('mirgee.configs.chatgpt')
require('mirgee.configs.octo')
