require('mirgee.configs.lspconfig')
-- require('mirgee.configs.copilot')
require('mirgee.configs.rust')
require('mirgee.configs.nvim-tree')
require('mirgee.configs.gitsigns')
require('mirgee.configs.telescope')
require('mirgee.configs.lualine')
require('mirgee.configs.undotree')
require('mirgee.configs.treesitter')
require('mirgee.configs.trouble')
require('mirgee.configs.lsp-signature')
require('mirgee.configs.snippets')
require('mirgee.configs.completion')
require('mirgee.configs.mason')
